AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/RedundantLineBreak:
  InspectBlocks: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/BlockForwarding:
  EnforcedStyle: explicit

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/Documentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/SingleLineDoEndBlock:
  Enabled: false
