name: CI
on:
  push:
    branches: [master]
  pull_request:
permissions:
  contents: read
jobs:
  specs:
    name: Specs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
          - "4.0"
          - jruby-10.0
          - jruby-10.1
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: rake ${{ matrix.ruby }}
        run: bundle exec rspec

  specs_successful:
    name: Specs passing?
    needs: specs
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          if ${{ needs.specs.result == 'success' }}
          then
            echo "All specs passed"
          else
            echo "Some specs failed"
            false
          fi

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - run: bundle exec rubocop
